apiVersion: v1
kind: Service
metadata:
  name: timescaledb-reader
spec:
  selector:
    app: timescaledb-reader
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  - name: probes
    port: 9091
    targetPort: probes
