apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
#  - prometheus-service-monitor.yaml

commonLabels:
  app: timescaledb-writer
