apiVersion: v1
kind: Service
metadata:
  name: timescaledb-writer
spec:
  selector:
    app: timescaledb-writer
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
  - name: probes
    port: 9091
    targetPort: probes
