apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-access
  labels:
    app: timescaledb
type: Opaque
data:
  # password-superuser: dGVh
  password-superuser: c3VwZXJzZWNyZXQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-data
  labels:
    app: timescaledb
type: Opaque
data:
  # password-superuser: Y29mZmVl
  password-superuser: c3VwZXJzZWNyZXQ=
