apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
    timescaleNodeType: access
spec:
  selector:
    app: timescaledb
    timescaleNodeType: access
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-data
  labels:
    app: timescaledb
    timescaleNodeType: data
spec:
  clusterIP: None
  selector:
    app: timescaledb
    timescaleNodeType: data
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
